"""ai_decision_engine.py — the brain.

Application-layer orchestrator, same pattern as the rest of this
package. Collects the outputs of every other agent (MarketAgent,
FiiDiiAgent, NewsAgent, MarketSentimentAgent, StrategyAgent) and
produces one final BUY / SELL / WAIT call with reasoning, confidence,
risk level, market bias, expected move, and a probability estimate.

This engine issues no orders and connects to no broker -- "BUY"/"SELL"
here means "this system's paper-trading setup leans long/short", never
an instruction sent anywhere. Every decision payload carries an explicit
`disclaimer` field for exactly this reason: this is a heuristic,
rule-based signal generator over the data this codebase can actually
fetch (FII/DII flows, options positioning, VIX, news keywords, and a
volatility-implied expected move) -- not investment advice, not a
statistically calibrated probability model, and not a substitute for a
human's own judgment or a licensed advisor.

Decision rule (deliberately simple and auditable rather than a black
box): BUY/SELL requires the overall market score to clear a threshold
AND the sentiment confidence to clear a minimum AND at least one
generated strategy to show an acceptable risk/reward. Otherwise: WAIT.
Every threshold is a constructor parameter (DecisionThresholds), not a
buried constant, so the rule can be audited and retuned without editing
this class's logic.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any

from titan_ai_trader.application.services.fii_dii_agent import FiiDiiAgent
from titan_ai_trader.application.services.market_agent import MarketAgent
from titan_ai_trader.application.services.market_data_service import MarketDataService
from titan_ai_trader.application.services.market_sentiment_agent import MarketSentimentAgent
from titan_ai_trader.application.services.news_agent import NewsAgent
from titan_ai_trader.application.services.strategy_agent import (
    ExpectedMoveCalculator,
    StrategyAgent,
    StrategySignal,
)
from titan_ai_trader.domain.exceptions.market_data_exceptions import MarketDataError

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This output is generated by a rule-based paper-trading signal engine. "
    "It is not investment advice, not a statistically calibrated probability, "
    "and not an instruction to trade. No order is or can be placed by this system."
)


def _utcnow() -> datetime:
    return datetime.now(UTC)


class Decision(StrEnum):
    BUY = "BUY"
    SELL = "SELL"
    WAIT = "WAIT"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class MarketBias(StrEnum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


@dataclass(frozen=True, slots=True)
class DecisionThresholds:
    """Every numeric cutoff the decision rule uses, in one auditable place."""

    buy_score_threshold: Decimal = Decimal("62")
    sell_score_threshold: Decimal = Decimal("38")
    min_confidence_pct: Decimal = Decimal("40")
    min_risk_reward: Decimal = Decimal("1.5")
    bias_neutral_band: Decimal = Decimal("10")  # |raw_score| below this = NEUTRAL bias
    vix_low_high: Decimal = Decimal("13")
    vix_high_low: Decimal = Decimal("20")

    def __post_init__(self) -> None:
        if not (Decimal("0") <= self.sell_score_threshold < self.buy_score_threshold <= Decimal("100")):
            raise ValueError("Require 0 <= sell_score_threshold < buy_score_threshold <= 100.")
        if not (Decimal("0") <= self.min_confidence_pct <= Decimal("100")):
            raise ValueError("min_confidence_pct must be in [0, 100].")
        if self.min_risk_reward <= 0:
            raise ValueError("min_risk_reward must be positive.")


@dataclass(frozen=True, slots=True)
class DecisionResult:
    decision: Decision
    reason: tuple[str, ...]
    confidence: Decimal
    risk_level: RiskLevel
    market_bias: MarketBias
    expected_move: Decimal
    probability_pct: Decimal
    overall_market_score: Decimal
    best_strategy: StrategySignal | None
    symbol: str
    disclaimer: str = DISCLAIMER
    generated_at: datetime = field(default_factory=_utcnow)


class DecisionJsonSerializer:
    @staticmethod
    def serialize(result: DecisionResult) -> dict[str, Any]:
        from titan_ai_trader.application.services.strategy_agent import StrategyJsonSerializer

        return {
            "symbol": result.symbol,
            "decision": result.decision.value,
            "reason": list(result.reason),
            "confidence": str(result.confidence),
            "risk_level": result.risk_level.value,
            "market_bias": result.market_bias.value,
            "expected_move": str(result.expected_move),
            "probability_pct": str(result.probability_pct),
            "overall_market_score": str(result.overall_market_score),
            "best_strategy": (
                StrategyJsonSerializer.serialize_signal(result.best_strategy)
                if result.best_strategy is not None
                else None
            ),
            "disclaimer": result.disclaimer,
            "generated_at": result.generated_at.isoformat(),
        }


class AiDecisionEngine:
    """Collects every agent's output and issues the final BUY/SELL/WAIT
    call. This is the top-level "brain" of the system -- everything else
    in the codebase feeds into this class; this class feeds nothing back
    into any of them, and has no broker/order-execution dependency.
    """

    def __init__(
        self,
        market_agent: MarketAgent,
        fii_dii_agent: FiiDiiAgent,
        news_agent: NewsAgent,
        market_sentiment_agent: MarketSentimentAgent,
        strategy_agent: StrategyAgent,
        market_data_service: MarketDataService,
        thresholds: DecisionThresholds | None = None,
        json_serializer: type[DecisionJsonSerializer] = DecisionJsonSerializer,
        engine_logger: logging.Logger | None = None,
    ) -> None:
        self._market_agent = market_agent
        self._fii_dii_agent = fii_dii_agent
        self._news_agent = news_agent
        self._sentiment_agent = market_sentiment_agent
        self._strategy_agent = strategy_agent
        self._market_data_service = market_data_service
        self._thresholds = thresholds or DecisionThresholds()
        self._serializer = json_serializer
        self._logger = engine_logger or logger

    def _classify_risk_level(self, vix_value: Decimal) -> RiskLevel:
        if vix_value < self._thresholds.vix_low_high:
            return RiskLevel.LOW
        if vix_value < self._thresholds.vix_high_low:
            return RiskLevel.MEDIUM
        return RiskLevel.HIGH

    def _classify_bias(self, raw_score: Decimal) -> MarketBias:
        if raw_score > self._thresholds.bias_neutral_band:
            return MarketBias.BULLISH
        if raw_score < -self._thresholds.bias_neutral_band:
            return MarketBias.BEARISH
        return MarketBias.NEUTRAL

    @staticmethod
    def _best_strategy(signals: list[StrategySignal]) -> StrategySignal | None:
        if not signals:
            return None
        # "Best" = highest RR on target 2, among strategies with a nonzero
        # position size (a zero-sized signal was already deemed too low
        # confidence to act on by StrategyAgent).
        sized = [s for s in signals if s.position_size > 0]
        pool = sized or signals
        return max(pool, key=lambda s: s.risk_reward_2)

    def get_decision_json(self, symbol: str = "NIFTY") -> dict[str, Any]:
        self._logger.info("Computing AI decision for %s", symbol)

        sentiment = self._sentiment_agent.get_market_sentiment_json()
        overall_score = Decimal(sentiment["overall_score_0_100"])
        raw_score = Decimal(sentiment["raw_score_neg100_100"])
        confidence = Decimal(sentiment["confidence_pct"])

        vix = self._market_data_service.get_india_vix()
        risk_level = self._classify_risk_level(vix.value)
        market_bias = self._classify_bias(raw_score)

        index_report = self._market_agent.analyze_index(symbol)
        expected_move = ExpectedMoveCalculator.daily_move(index_report.spot.last_price.amount, vix.value)

        strategy_signals = self._strategy_agent.generate_all_strategies(symbol)
        best_strategy = self._best_strategy(strategy_signals)

        best_rr = best_strategy.risk_reward_2 if best_strategy is not None else Decimal("0")
        meets_confidence = confidence >= self._thresholds.min_confidence_pct
        meets_rr = best_rr >= self._thresholds.min_risk_reward

        reason: list[str] = list(sentiment["reasoning"])
        try:
            fii_dii = self._fii_dii_agent.get_fii_dii_report_json(activity_date=None)
            reason.append(
                f"Institutional sentiment: {fii_dii['institutional_sentiment']['label']} "
                f"(score {fii_dii['institutional_sentiment']['total_score']})"
            )
        except MarketDataError as exc:
            self._logger.warning("FII/DII context unavailable for decision reasoning: %s", exc)

        try:
            news = self._news_agent.get_market_news_json()
            reason.append(
                f"News sentiment: {news['overall_sentiment']['label']} "
                f"({news['overall_sentiment']['total_articles']} article(s), "
                f"{len(news['high_impact_alerts'])} high-impact alert(s))"
            )
        except Exception as exc:  # noqa: BLE001 - news is a secondary signal
            self._logger.warning("News context unavailable for decision reasoning: %s", exc)

        reason.append(f"VIX {vix.value} -> risk level {risk_level.value}")
        if best_strategy is not None:
            reason.append(
                f"Best strategy: {best_strategy.strategy_type.value} "
                f"({best_strategy.direction.value}) RR2={best_strategy.risk_reward_2}"
            )
        else:
            reason.append("No strategy could be generated (insufficient market data).")

        if overall_score >= self._thresholds.buy_score_threshold and meets_confidence and meets_rr:
            decision = Decision.BUY
        elif overall_score <= self._thresholds.sell_score_threshold and meets_confidence and meets_rr:
            decision = Decision.SELL
        else:
            decision = Decision.WAIT
            if not meets_confidence:
                reason.append(
                    f"WAIT: confidence {confidence}% below minimum "
                    f"{self._thresholds.min_confidence_pct}%."
                )
            if not meets_rr:
                reason.append(
                    f"WAIT: best available risk/reward {best_rr} below minimum "
                    f"{self._thresholds.min_risk_reward}."
                )
            if self._thresholds.sell_score_threshold < overall_score < self._thresholds.buy_score_threshold:
                reason.append(
                    f"WAIT: overall market score {overall_score} is within the neutral band "
                    f"({self._thresholds.sell_score_threshold}-{self._thresholds.buy_score_threshold})."
                )

        # Heuristic mapping from confidence to a probability-like figure --
        # NOT a calibrated statistical probability. Bounded to [5, 95] so
        # this never claims false certainty in either direction.
        probability_pct = max(Decimal("5"), min(Decimal("95"), confidence))

        result = DecisionResult(
            decision=decision,
            reason=tuple(reason),
            confidence=confidence,
            risk_level=risk_level,
            market_bias=market_bias,
            expected_move=expected_move,
            probability_pct=probability_pct,
            overall_market_score=overall_score,
            best_strategy=best_strategy,
            symbol=symbol,
        )

        self._logger.info(
            "Decision for %s: %s (confidence=%s%%, risk=%s, bias=%s)",
            symbol,
            decision.value,
            confidence,
            risk_level.value,
            market_bias.value,
        )
        return self._serializer.serialize(result)

    def get_decision_json_string(self, indent: int | None = 2, **kwargs: Any) -> str:
        return json.dumps(self.get_decision_json(**kwargs), indent=indent)
